x-service-builder: &builder
  context: ../
  platforms:
    - "linux/amd64"
  dockerfile: dockerfiles/Dockerfile

services:
  application:
    build:
      target: runtime
      <<: *builder
    container_name: application
    

  application_test:
    build:
      target: test
      <<: *builder
    container_name: application_test
