name: Run unit tests

on:
  - pull_request
  - workflow_dispatch

jobs:
  run-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Prepare environment
        uses: actions/setup-python@v3
        with:
          python-version: 3.12
      - name: Run unit tests
        run: make test-docker
